# Generated by Django 3.1.3 on 2021-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210114_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='powerpoint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
