# Generated by Django 3.1.3 on 2021-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210114_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
