# Generated by Django 3.1.3 on 2021-02-04 15:53

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('content', mdeditor.fields.MDTextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
